[package]
name = "tree-display-derive"
authors = ["Cezar Petriuc <contact@czrptr.com>"]
repository = "https://github.com/czrptr/tree-display"
documentation = "https://docs.rs/tree-display-derive/latest/tree-display-derive"
description = """
Procedural macro implementation for tree-display.
Derives TreeDisplay for rendering data structures as syntax-highlighted trees.
"""
categories = ["development-tools::procedural-macro-helpers"]

version = "1.0.1"
edition = "2021"
rust-version = "1.75"
readme = "README.md"
license = "MIT"
license-file = "../LICENSE"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3.5"
proc-macro2 = "1.0"
darling = "0.23"
quote = "1.0"
syn = "2.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
